### ISSUE TITLE
Add normal E2 execution loop

### ISSUE THREAD

**Issue by TitusStudiosMediaGroup** [ZZ-Cat/Self-Updatable-E2-Kernel#3]
Add a default execution loop to the `main.txt` (@`../e2shared/mySelfUpdatableE2/main.txt`)
This would allow code to be ran with its own interval (rather than running on tick).

### Main Process:
```lua
#[ Execute application code. ]#
default()
if(tickClk()){ loop() }
if(inputClk()){ inputEvent() }
```

### Example:
```lua
    function void default(){
        print("Hello, World!")
    }
```

**Comment by ZZ-Cat** [comment]
I'll add that in the next major update on this. I actually want to rewrite the entire code for this, as I'm still not happy with the way it's working as it is, now.

I also have bugger-all internet access, so that's slowed down working on this as well.

What I have found out is, I have inadvertently made it difficult to link this kernel to different sources for user code (oops).
I'll also streamline a lot of the code as well. EG Getting rid of a lot of the "include" files. What I had in those files can get transferred straight into the main file anyways.

**Comment by TitusStudiosMediaGroup** [comment]
Yeah would say that getting around how the system works is bit of a hassle. Will have a look. I lost my edited version plus Im on a new drive.

**Comment by ZZ-Cat** [comment]
Oof! That's one of the reasons why I started my GitHub in the first place... If I lost any of my software projects, it's all backed up on GitHub.

But, yeah, I actually started working on the next major update today. When I'm next around some internet (aside from my phone), I'll get that up here; test it out & see what happens; & go from there.

**Comment by TitusStudiosMediaGroup** [comment]
Awesome! Hope you guys get some better internez down there. Hope everything is going swell

**Comment by ZZ-Cat** [comment]
I got 'er done!
Sorry, it took so long for me to do it. But, it's there anyways.
I ain't had a chance to test it out yet. So, yeah. Look for 'defaultE2handler()' & lemme know how ya get on with it. =^/,..,^=

**Comment by TitusStudiosMediaGroup** [comment]
I would consider this e2 solution to be deprecated, have moved to lua based options, which are more reliable and use less resources. Cheers anyways!
